const galleryItems = {
  "construction-existing-foundation":
      [
      { id: "img001",imageUrl: "images/img-1-foundation.jpg", title: "initial view south 1", shortAnnotation: "excavated south foundation wall", fullAnnotation: "original foundation wall - no damp-proofing" },
      { id: "img002",imageUrl: "images/img-2-foundation.jpg", title: "initial view south 1", shortAnnotation: "excavated north foundation wall", fullAnnotation: "original foundation wall - no damp-proofing" },
      { id: "img003",imageUrl: "images/img-3-foundation.jpg", title: "initial view north 1", shortAnnotation: "excavated south foundation wall", fullAnnotation: "original foundation wall - no damp-proofing" },
      { id: "img004",imageUrl: "images/img-4-foundation.jpg", title: "foundation coating prep 2", shortAnnotation: "foundation coating prep", fullAnnotation: "clear debris from foundation wall" },
      { id: "img005",imageUrl: "images/img-5-foundation.jpg", title: "waterproofing", shortAnnotation: "applying water proofing", fullAnnotation: "apply waterproofing" },
      { id: "img006",imageUrl: "images/img-6-foundation.jpg", title: "foundation drains", shortAnnotation: "foundation drains and backfill", fullAnnotation: "footing drain and gutter drains in the backfill" },
      { id: "img007",imageUrl: "images/img-7-foundation.jpg", title: "foundation backfill", shortAnnotation: "foundation backfill", fullAnnotation: "backfill crushed stone, filter fabric and sand" },
    ],
  "construction-additions":
    [
      { id: "img010",imageUrl: "images/img-1-additions.jpg", title: "north addition excavation", shortAnnotation: "new entries", fullAnnotation: "new entries" },
      { id: "img011",imageUrl: "images/img-2-additions.jpg", title: "west addition excavation", shortAnnotation: "new storage and mechanical", fullAnnotation: "new storage and mechanical" },
      { id: "img012",imageUrl: "images/img-3-additions.jpg", title: "north addition footings", shortAnnotation: "north addition footings", fullAnnotation: "north addition footings" },
      { id: "img013",imageUrl: "images/img-4-additions.jpg", title: "west addition footings", shortAnnotation: "west addition footings", fullAnnotation: "west addition footings" },
      { id: "img014",imageUrl: "images/img-5-additions.jpg", title: "concrete placement", shortAnnotation: "concrete placement", fullAnnotation: "west addition footings concrete placement" },
      { id: "img015",imageUrl: "images/img-6-additions.jpg", title: "rerod for wall connection", shortAnnotation: "rerod for wall connection", fullAnnotation: "reinforcing rod for existing foundation wall connection" },
      { id: "img016",imageUrl: "images/img-7-additions.jpg", title: "wall forms ready for concrete", shortAnnotation: "wall forms ready for concrete", fullAnnotation: "wall forms ready for concrete" },
      { id: "img017",imageUrl: "images/img-8-additions.jpg", title: "wall forms reinforcing steel", shortAnnotation: "wall forms reionforcing steel", fullAnnotation: "new wall's connecting steel to existing foundation wall" },
      { id: "img018",imageUrl: "images/img-9-additions.jpg", title: "west addition foundation walls", shortAnnotation: "west addition foundation walls", fullAnnotation: "west addition finished walls including anchor bolts" },
      { id: "img019",imageUrl: "images/img-10-additions.jpg", title: "north addition concrete floor preparation", shortAnnotation: "north addition concrete floor preparation", fullAnnotation: "slab backfill with crushed stone. floor drains to sump pump, one per addition" },
      { id: "img020",imageUrl: "images/img-11-additions.jpg", title: "concrete cutting", shortAnnotation: "concrete cutting", fullAnnotation: "cut access to existing crawl space" },
      { id: "img022",imageUrl: "images/img-12-additions.jpg", title: "concrete cutting", shortAnnotation: "concrete cutting", fullAnnotation: "crawl space wall cutout toppling out " },
      { id: "img021",imageUrl: "images/img-13-additions.jpg", title: "slab preparation", shortAnnotation: "slab preparation", fullAnnotation: "slab preparation includes two layers of 6 mil polyethelene" },
      { id: "img023",imageUrl: "images/img-14-additions.jpg", title: "floor concrete placement", shortAnnotation: "floor concrete placement", fullAnnotation: "concrete placement for the west addition by MacDonald Concrete" },
    ],      
      "construction-der-envelope":
    [
      { id: "img000",imageUrl: "images/img-0-envelope.jpg", title: "initial view north 1", shortAnnotation: "initial view", fullAnnotation: "original roof: pre-retrofit condition: trusses with a foot of eave overhang and gable end overhangs" },
      { id: "img001",imageUrl: "images/img-1-envelope.jpg", title: "initial view north 2", shortAnnotation: "initial view north 2", fullAnnotation: "original envelope wall : 2x6 with fiberglass cavity insulation" },
      { id: "img002",imageUrl: "images/img-2-envelope.jpg", title: "1 siding and roof overhangs removed", shortAnnotation: "siding and roof overhangs removed", fullAnnotation: "a section of removed eave overhang" },
      { id: "img003",imageUrl: "images/img-3-envelope.jpg", title: "2 remove siding", shortAnnotation: "2 remove siding", fullAnnotation: "remove existing vinyl siding " },
      { id: "img004",imageUrl: "images/img-4-envelope.jpg", title: "3 roof and eave protection", shortAnnotation: "3 roof and eave protection", fullAnnotation: "siding and roofing removed exposing existing sheathing, then add underlayment (Roof Guard II) for water protection and air sealing of wall-roof joint" },
      { id: "img005",imageUrl: "images/img-5-envelope.jpg", title: "4 insulation", shortAnnotation: "4 insulation", fullAnnotation: "add two layers of 2 in. polyiso insulation (Tuff R Enerfoil, R=6.5 per inch), onto the roof deck, staggering the joints" },
      { id: "img006",imageUrl: "images/img-6-envelope.jpg", title: "5 2x4s over roof insulation", shortAnnotation: "5 2x4s over roof insulation", fullAnnotation: "screw flat 2x4s (8 in. screws, Simpson SDWS) securing insulation and creating a venting path from eave to ridge. The 2x4s will support a new overhang " },
      { id: "img007",imageUrl: "images/img-7-envelope.jpg", title: "5 2x4s over roof insulation", shortAnnotation: "5 2x4s over roof insulation", fullAnnotation: "screw flat 2x4s (8 in. screws, Simpson SDWS) securing insulation and creating a venting path from eave to ridge. The 2x4s will support a new overhang " },
      { id: "img008",imageUrl: "images/img-8-envelope.jpg", title: "6 roof decking", shortAnnotation: "6 roof decking", fullAnnotation: "add roof decking (5/8 in. Advantech)" },
      { id: "img009",imageUrl: "images/img-9-envelope.jpg", title: "6 deck completed", shortAnnotation: "6 deck completed", fullAnnotation: "roof decking completed" },
      { id: "img010",imageUrl: "images/img-10-envelope.jpg", title: "7 construct new overhangs", shortAnnotation: "construct new overhangs", fullAnnotation: "construct new overhangs" },
      { id: "img011",imageUrl: "images/img-11-envelope.jpg", title: "7 overhangs", shortAnnotation: "overhangs", fullAnnotation: "bnew overhangs and soffits with rough facia" },
      { id: "img012",imageUrl: "images/img-12-envelope.jpg", title: "8 facia", shortAnnotation: "facia", fullAnnotation: "install eave and rake facia (Azek). note: shed to be relocated on site" },
      { id: "img013",
        imageUrl: "images/img-9-1-remove-existing.jpg", 
        title: "9 windows: remove existing ", 
        shortAnnotation: "remove existing windows", 
        fullAnnotation: "remove existing double hung, double-pane, aluminum frame windows, 2004" },
      { id: "img014",
        imageUrl: "images/img-9-2-1-extension-framing.jpg", 
        title: "9-1 windows: extend existing framing", 
        shortAnnotation: "extend window framing", 
        fullAnnotation: "extend existing framing out to accomodate 2 in. exterior insulation" },
      { id: "img015",
        imageUrl: "images/img-9-2-2-extension-framing.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img016",
        imageUrl: "images/img-9-3-1-new-window-prep.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img017",
        imageUrl: "images/img-9-4-1-new-window-set.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img018",
        imageUrl: "images/img-9-4-2-new-window-set.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img019",
        imageUrl: "images/img-9-4-3-new-window-set.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img020",
        imageUrl: "images/img-9-4-4-new-window-set.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },
      { id: "img021",
        imageUrl: "images/img-9-4-5-new-window-set-taped.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },

      { id: "img022",imageUrl: "images/img-13-envelope.jpg", title: "10 exterior wall insulation", shortAnnotation: "exterior wall insulation and sheathing", fullAnnotation: "install 2 in. polyiso exterior wall insulation covered with ZipSystem sheathing" }
    ],

    "construction-party-walls": [
      { id: "img001",
        imageUrl: "images/img-1-party-walls.jpg", 
        title: "original wall between kitchens from Unit 1", 
        shortAnnotation: "original wall between kitchens from Unit 1", 
        fullAnnotation: "the original party wall was a staggered stud 2x6 with two layers of 5/8 drywall on one side, one layer on the other side; it was demolished" },
      { id: "img002",
        imageUrl: "images/img-2-party-walls.jpg", 
        title: "new fire and sound separation wall of type #1", 
        shortAnnotation: "new party wall of type 1 see drawing A-9", 
        fullAnnotation: "the new party walls for kitchens and entries are double stagered stud walls with 1 in. separation" },
      { id: "img003",
        imageUrl: "images/img-3-party-walls.jpg", 
        title: "framing of party walls separating kitchens and new entries", 
        shortAnnotation: "new walls separating kitchens and entries", 
        fullAnnotation: "the new party wall is a double stagered stud wall with 1 in. separation " },
      { id: "img004",
        imageUrl: "images/img-4-party-walls.jpg", 
        title: "cavity insulation for sound walls", 
        shortAnnotation: "cavity insulation for sound walls", 
        fullAnnotation: "each wall insulated with Roxel Safe and Sound cavity insulation" },   
      { id: "img005",
        imageUrl: "images/img-5-party-walls.jpg", 
        title: "sound walls for new bathrooms, Wall #2, drawing A-9 ", 
        shortAnnotation: "sound walls for new bathrooms", 
        fullAnnotation: "Wall #2 is a 2x8 staggered stud wall with two layers of 5/8 in drywall on one side and two layers of 5/8 in drywall over a layer of resilient channel RC-1 on the other side" },
      { id: "img006",
        imageUrl: "images/img-6-party-walls.jpg", 
        title: "bathroom walls with cavity insulation and resilient channel", 
        shortAnnotation: "bathroom walls with cavities filled", 
        fullAnnotation: "each wall insulated with Roxel Safe and Sound cavity insulation" }, 
      { id: "img007",
        imageUrl: "images/img-7-party-walls.jpg", 
        title: "layer 1 of 5/8 in fireblock drywall", 
        shortAnnotation: "bathroom walls with cavities filled", 
        fullAnnotation: "layer 1 of 5/8 in fireblock drywall on Unit 1 kitchen" },    
      { id: "img008",
        imageUrl: "images/img-8-party-walls.jpg", 
        title: "layer 1 of 5/8 in fireblock drywall", 
        shortAnnotation: "layer 1 of 5/8 in fireblock drywall", 
        fullAnnotation: "layer 1 of 5/8 in fireblock drywall with screws and joints caulked and filled" },      
      { id: "img009",
        imageUrl: "images/img-9-party-walls.jpg", 
        title: "layer 2 of 5/8 in fireblock drywall with Greenglue", 
        shortAnnotation: "layer 2 of 5/8 in fireblock drywall", 
        fullAnnotation: "layer 2 of 5/8 in fireblock drywall with Greenglue applied to back of each panel to damp sound between layers" },  


    ]

  }
  export default galleryItems
  /*
      { id: "img015",
        imageUrl: "images/img-9-.jpg", 
        title: "", 
        shortAnnotation: "", 
        fullAnnotation: "" },



  */